/**
 * Cloudflare Workers platform adapter.
 *
 * Bundles all dependencies, needs client manifest for lazy chunk
 * injection, and performs post-build global injection + _headers generation.
 */
import type { PlatformAdapter, BuildContext } from "../core/platform.js";
import { computeLazyChunks } from "../core/types.js";
import path from "node:path";
import fs from "node:fs";

export class CloudflareAdapter implements PlatformAdapter {
  readonly name = "cloudflare" as const;
  readonly bundlesAllDeps = true;
  readonly needsClientManifest = true;

  rscExternals(): string[] {
    return [];
  }

  async onBuildComplete(ctx: BuildContext): Promise<void> {
    const clientDir = path.resolve(ctx.root, "dist", "client");

    // Read build manifest and compute lazy chunks
    let lazyChunksData: string[] | null = null;
    let clientEntryFile: string | null = null;
    const buildManifestPath = path.join(clientDir, ".vite", "manifest.json");
    if (fs.existsSync(buildManifestPath)) {
      try {
        const buildManifest = JSON.parse(fs.readFileSync(buildManifestPath, "utf-8"));
        for (const [, value] of Object.entries(buildManifest) as [string, any][]) {
          if (value && value.isEntry && value.file) {
            clientEntryFile = value.file;
            break;
          }
        }
        const lazy = computeLazyChunks(buildManifest);
        if (lazy.length > 0) lazyChunksData = lazy;
      } catch { /* ignore parse errors */ }
    }

    // Read SSR manifest
    let ssrManifestData: Record<string, string[]> | null = null;
    const ssrManifestPath = path.join(clientDir, ".vite", "ssr-manifest.json");
    if (fs.existsSync(ssrManifestPath)) {
      try {
        ssrManifestData = JSON.parse(fs.readFileSync(ssrManifestPath, "utf-8"));
      } catch { /* ignore parse errors */ }
    }

    if (ctx.hasAppDir) {
      // App Router
      const workerEntry = path.resolve(ctx.distDir, "server", "index.js");
      if (fs.existsSync(workerEntry) && (lazyChunksData || ssrManifestData)) {
        let code = fs.readFileSync(workerEntry, "utf-8");
        const globals: string[] = [];
        if (ssrManifestData) {
          globals.push(`globalThis.__OPENVITE_SSR_MANIFEST__ = ${JSON.stringify(ssrManifestData)};`);
        }
        if (lazyChunksData) {
          globals.push(`globalThis.__OPENVITE_LAZY_CHUNKS__ = ${JSON.stringify(lazyChunksData)};`);
        }
        code = globals.join("\n") + "\n" + code;
        fs.writeFileSync(workerEntry, code);
      }
    } else {
      // Pages Router
      let workerOutDir: string | null = null;
      for (const entry of fs.readdirSync(ctx.distDir)) {
        const candidate = path.join(ctx.distDir, entry);
        if (entry === "client") continue;
        if (fs.statSync(candidate).isDirectory() &&
            fs.existsSync(path.join(candidate, "wrangler.json"))) {
          workerOutDir = candidate;
          break;
        }
      }
      if (!workerOutDir) return;

      const workerEntry = path.join(workerOutDir, "index.js");
      if (!fs.existsSync(workerEntry)) return;

      if (!clientEntryFile) {
        const assetsDir = path.join(clientDir, "assets");
        if (fs.existsSync(assetsDir)) {
          const files = fs.readdirSync(assetsDir);
          const entry = files.find((f: string) =>
            (f.includes("openvite-client-entry") || f.includes("openvite-app-browser-entry")) && f.endsWith(".js"));
          if (entry) clientEntryFile = "assets/" + entry;
        }
      }

      if (clientEntryFile || ssrManifestData || lazyChunksData) {
        let code = fs.readFileSync(workerEntry, "utf-8");
        const globals: string[] = [];
        if (clientEntryFile) {
          globals.push(`globalThis.__OPENVITE_CLIENT_ENTRY__ = ${JSON.stringify(clientEntryFile)};`);
        }
        if (ssrManifestData) {
          globals.push(`globalThis.__OPENVITE_SSR_MANIFEST__ = ${JSON.stringify(ssrManifestData)};`);
        }
        if (lazyChunksData) {
          globals.push(`globalThis.__OPENVITE_LAZY_CHUNKS__ = ${JSON.stringify(lazyChunksData)};`);
        }
        code = globals.join("\n") + "\n" + code;
        fs.writeFileSync(workerEntry, code);
      }
    }

    // Generate _headers file for immutable asset caching
    const headersPath = path.join(clientDir, "_headers");
    if (!fs.existsSync(headersPath)) {
      const assetsDir = ctx.envConfig?.build?.assetsDir ?? "assets";
      const headersContent = [
        "# Cache content-hashed assets immutably (generated by openvite)",
        `/${assetsDir}/*`,
        "  Cache-Control: public, max-age=31536000, immutable",
        "",
      ].join("\n");
      fs.writeFileSync(headersPath, headersContent);
    }
  }
}
